### ISSUE TITLE
Docker Servisi Sorunu

### ISSUE THREAD

**Issue by MuhammetDilmac** [pisilinux/main#2003]
Ara ara docker servisini başlatırkan **plasmashell** çöküyor hata bilgileri burada;

```
Application: Plasma (plasmashell), signal: Aborted
[KCrash Handler]
#5  0x00007f29619943e8 in raise () from /lib/libc.so.6
#6  0x00007f2961995fea in abort () from /lib/libc.so.6
#7  0x00007f2962132bde in QMessageLogger::fatal(char const*, ...) const () from /usr/lib/libQt5Core.so.5
#8  0x00007f29630d22b2 in ?? () from /usr/lib/libQt5DBus.so.5
#9  0x00007f2962354348 in ?? () from /usr/lib/libQt5Core.so.5
#10 0x00007f29623551ef in QVariant::QVariant(int, void const*) () from /usr/lib/libQt5Core.so.5
#11 0x00007f2962323002 in QMetaProperty::read(QObject const*) const () from /usr/lib/libQt5Core.so.5
#12 0x00007f2962341e2f in QObject::property(char const*) const () from /usr/lib/libQt5Core.so.5
#13 0x00007f29678740e6 in ?? () from /usr/lib/libKF5Solid.so.5
#14 0x00007f296786ce61 in ?? () from /usr/lib/libKF5Solid.so.5
#15 0x00007f296788acb9 in ?? () from /usr/lib/libKF5Solid.so.5
#16 0x00007f296786d5de in ?? () from /usr/lib/libKF5Solid.so.5
#17 0x00007f29678250a9 in Solid::Device::emblems() const () from /usr/lib/libKF5Solid.so.5
#18 0x00007f289be49f2c in ?? () from /usr/lib/qt5/plugins/plasma/dataengine/plasma_engine_hotplug.so
#19 0x00007f289be4b9a1 in ?? () from /usr/lib/qt5/plugins/plasma/dataengine/plasma_engine_hotplug.so
#20 0x00007f296234324a in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
#21 0x00007f29678268b2 in Solid::DeviceNotifier::deviceAdded(QString const&) () from /usr/lib/libKF5Solid.so.5
#22 0x00007f296234324a in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
#23 0x00007f2967896482 in ?? () from /usr/lib/libKF5Solid.so.5
#24 0x00007f2967864b0c in ?? () from /usr/lib/libKF5Solid.so.5
#25 0x00007f296789a72d in ?? () from /usr/lib/libKF5Solid.so.5
#26 0x00007f296234324a in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
#27 0x00007f296789a9bc in ?? () from /usr/lib/libKF5Solid.so.5
#28 0x00007f296789f105 in ?? () from /usr/lib/libKF5Solid.so.5
#29 0x00007f29630b0743 in ?? () from /usr/lib/libQt5DBus.so.5
#30 0x00007f2962344039 in QObject::event(QEvent*) () from /usr/lib/libQt5Core.so.5
#31 0x00007f296345ebfc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#32 0x00007f2963463d06 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#33 0x00007f2962315fc3 in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#34 0x00007f29623182e6 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/libQt5Core.so.5
#35 0x00007f29623693f3 in ?? () from /usr/lib/libQt5Core.so.5
#36 0x00007f295ded5fd7 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#37 0x00007f295ded6208 in ?? () from /usr/lib/libglib-2.0.so.0
#38 0x00007f295ded62ac in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#39 0x00007f29623697ff in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#40 0x00007f296231390a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#41 0x00007f296231b5cd in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#42 0x000000000041bf1d in ?? ()
#43 0x00007f296197f7a0 in __libc_start_main () from /lib/libc.so.6
#44 0x000000000041c049 in _start ()
```

**Comment by ertugerata** [comment]
tekrarlanamıyor ?

**Comment by MuhammetDilmac** [comment]
@ertugerata anlamadım abi

**Comment by ertugerata** [comment]
bende olmuyor bu hata, sende devam ediyor mu?

**Comment by MuhammetDilmac** [comment]
Evet abi devam ediyor her servis başlatmamda

**Comment by ertugerata** [comment]
docker in yenisini kurup,var/lib/docker dizinini  sildikten sonra dener misin? aufs-util bağımlılığı ile bende çökme gözükmezoldu graphdriver aufs kullanıyor varsayılan olarak.

**Comment by bferturk** [comment]
nm-connect paketiyle aynı grup  numarası verilmiş muhtemelen sorunun sebebi olabilir.baselayout paketine bakılıp öyle numaralandırılmalı

**Comment by ertugerata** [comment]
artık docker in grup numarası olmadığına göre tekrarlanmaması lazım. birisi kontrol edebilir mi ? bende çalışıyor. @MuhammetDilmac @alihanozturk
