### ISSUE TITLE
Pisi Linux 2.0 Alpha 3 Dolphin Çökmesi

### ISSUE THREAD

**Issue by MuhammetDilmac** [pisilinux/main#220]
Pisi Linux 2.0 Alpha 3'de Dolphin'i açtığımda çökmekte.

```bash
Application: Dolphin (dolphin), signal: Segmentation fault
To enable execution of this file add
	add-auto-load-safe-path /lib/libthread_db-1.0.so
line to your configuration file "/home/muhammet/.gdbinit".
To completely disable this security protection add
	set auto-load safe-path /
line to your configuration file "/home/muhammet/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
	info "(gdb)Auto-loading safe path"
[Current thread is 1 (LWP 17581)]

Thread 1 (LWP 17581):
#0  0x00007f92b90b1ddf in pthread_cond_wait () from /lib/libpthread.so.0
#1  0x00007f92b66eabc9 in ?? () from /usr/lib/libxcb.so.1
#2  0x00007f92b66ec04f in ?? () from /usr/lib/libxcb.so.1
#3  0x00007f92b66ec161 in xcb_wait_for_reply () from /usr/lib/libxcb.so.1
#4  0x00007f92af807f46 in ?? () from /usr/lib/qt5/plugins/platforms/libqxcb.so
#5  0x00007f92af807fda in ?? () from /usr/lib/qt5/plugins/platforms/libqxcb.so
#6  0x00007f92be76dde8 in QCursor::pos(QScreen const*) () from /usr/lib/libQt5Gui.so.5
#7  0x00007f92be76dec1 in QCursor::pos() () from /usr/lib/libQt5Gui.so.5
#8  0x00007f92bf06e9f5 in QMenu::internalDelayedPopup() () from /usr/lib/libQt5Widgets.so.5
#9  0x00007f92bdde109b in QObject::event(QEvent*) () from /usr/lib/libQt5Core.so.5
#10 0x00007f92bef3cdb7 in QWidget::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#11 0x00007f92bf073b53 in QMenu::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#12 0x00007f92beefc6ac in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#13 0x00007f92bef017b0 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#14 0x00007f92bddb1eb3 in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#15 0x00007f92bde055d5 in QTimerInfoList::activateTimers() () from /usr/lib/libQt5Core.so.5
#16 0x00007f92bde05a11 in ?? () from /usr/lib/libQt5Core.so.5
#17 0x00007f92b8979f1d in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#18 0x00007f92b897a1c8 in ?? () from /usr/lib/libglib-2.0.so.0
#19 0x00007f92b897a26c in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#20 0x00007f92bde0662c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#21 0x00007f92bddaf8d2 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#22 0x00007f92bf072330 in QMenu::exec(QPoint const&, QAction*) () from /usr/lib/libQt5Widgets.so.5
#23 0x00007f92c3cb7287 in ?? () from /usr/lib/libkdeinit5_dolphin.so
#24 0x00007f92c3cb8fad in ?? () from /usr/lib/libkdeinit5_dolphin.so
#25 0x00007f92c3cadbfc in ?? () from /usr/lib/libkdeinit5_dolphin.so
#26 0x00007f92bdddfa0a in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
#27 0x00007f92c3657634 in DolphinView::requestContextMenu(QPoint const&, KFileItem const&, QUrl const&, QList<QAction*> const&) () from /usr/lib/libdolphinprivate.so.5
#28 0x00007f92c36321dd in DolphinView::slotItemContextMenuRequested(int, QPointF const&) () from /usr/lib/libdolphinprivate.so.5
#29 0x00007f92bdddfa0a in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
#30 0x00007f92c3656506 in KItemListController::itemContextMenuRequested(int, QPointF const&) () from /usr/lib/libdolphinprivate.so.5
#31 0x00007f92c35e679c in KItemListController::mousePressEvent(QGraphicsSceneMouseEvent*, QTransform const&) () from /usr/lib/libdolphinprivate.so.5
#32 0x00007f92c35e76d4 in KItemListController::processEvent(QEvent*, QTransform const&) () from /usr/lib/libdolphinprivate.so.5
#33 0x00007f92c35fabe2 in KItemListView::event(QEvent*) () from /usr/lib/libdolphinprivate.so.5
#34 0x00007f92beefc6ac in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#35 0x00007f92bef017b0 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#36 0x00007f92bddb1eb3 in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#37 0x00007f92bf205e7e in ?? () from /usr/lib/libQt5Widgets.so.5
#38 0x00007f92bf206259 in ?? () from /usr/lib/libQt5Widgets.so.5
#39 0x00007f92bf20fe5a in ?? () from /usr/lib/libQt5Widgets.so.5
#40 0x00007f92bf210289 in QGraphicsScene::mousePressEvent(QGraphicsSceneMouseEvent*) () from /usr/lib/libQt5Widgets.so.5
#41 0x00007f92bf2199f8 in QGraphicsScene::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#42 0x00007f92beefc6ac in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#43 0x00007f92bef017b0 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#44 0x00007f92bddb1eb3 in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#45 0x00007f92bf23384f in QGraphicsView::mousePressEvent(QMouseEvent*) () from /usr/lib/libQt5Widgets.so.5
#46 0x00007f92bef3d239 in QWidget::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#47 0x00007f92bf0332ce in QFrame::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#48 0x00007f92bf234c73 in QGraphicsView::viewportEvent(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#49 0x00007f92bddb1ce6 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#50 0x00007f92beefc68c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#51 0x00007f92bef022e0 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#52 0x00007f92bddb1eb3 in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#53 0x00007f92bef00c32 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () from /usr/lib/libQt5Widgets.so.5
#54 0x00007f92bef54560 in ?? () from /usr/lib/libQt5Widgets.so.5
#55 0x00007f92bef5657b in ?? () from /usr/lib/libQt5Widgets.so.5
#56 0x00007f92beefc6ac in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#57 0x00007f92bef017b0 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#58 0x00007f92bddb1eb3 in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#59 0x00007f92be7642cd in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/libQt5Gui.so.5
#60 0x00007f92be765c35 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/libQt5Gui.so.5
#61 0x00007f92be74c5ef in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Gui.so.5
#62 0x00007f92af811670 in ?? () from /usr/lib/qt5/plugins/platforms/libqxcb.so
#63 0x00007f92b8979f1d in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#64 0x00007f92b897a1c8 in ?? () from /usr/lib/libglib-2.0.so.0
#65 0x00007f92b897a26c in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#66 0x00007f92bde06617 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#67 0x00007f92bddaf8d2 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#68 0x00007f92bddb6fdd in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#69 0x00007f92c3cc0b78 in kdemain () from /usr/lib/libkdeinit5_dolphin.so
#70 0x00007f92c38b99e0 in __libc_start_main () from /lib/libc.so.6
#71 0x0000000000400769 in _start ()
```

**Comment by ertugerata** [comment]
dolphin i git sürümünden unstable a çektim güncelleyipdener misin?

**Comment by ertugerata** [comment]
alfa4 te tekrarlanıyor mu?

**Comment by ertugerata** [comment]
stable/dolphin15.08.0 yayınandı kontrol eder misiniz. bende çalışıyor

**Comment by ertugerata** [comment]
hatanın devam edip etmediğine dair bir yorum yok bende çalışıyor gayette problemsiz. hata tekrar ederse yeniden açılabilir.

**Comment by MuhammetDilmac** [comment]
Sorun kalmadı teşekkürler. Geç geri dönüş için özür dilerim.
