### ISSUE TITLE
cups-filters - http://ciftlik.pisilinux.org/ciftlik/compiledetail/16019

### ISSUE THREAD

**Issue by Rmys** [pisilinux/main#3265]
Cups-filtres Rebuild edilmesi gerekiyor. Ancak derleme hatası verdi yeni sistemde kırık

./configure: line 19033: acroread: command not found
./configure: line 19373: ]: command not found
In file included from cupsfilters/colord.c:39:0:
cupsfilters/colord.h:39:44: error: unknown type name 'ppd_file_t'
 char  **colord_get_qualifier_for_ppd      (ppd_file_t *ppd);
                                            ^~~~~~~~~~
cupsfilters/colord.c:47:31: error: unknown type name 'ppd_file_t'
 colord_get_qualifier_for_ppd (ppd_file_t *ppd)
                               ^~~~~~~~~~
make[1]: *** [Makefile:2567: libcupsfilters_la-colord.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from cupsfilters/attr.c:26:0:
cupsfilters/driver.h:129:8: error: unknown type name 'ppd_attr_t'
 extern ppd_attr_t *cupsFindAttr(ppd_file_t *ppd, const char *name,
        ^~~~~~~~~~
cupsfilters/driver.h:129:33: error: unknown type name 'ppd_file_t'
 extern ppd_attr_t *cupsFindAttr(ppd_file_t *ppd, const char *name,
                                 ^~~~~~~~~~
cupsfilters/driver.h:159:32: error: unknown type name 'ppd_file_t'
 extern cups_lut_t *cupsLutLoad(ppd_file_t *ppd,
                                ^~~~~~~~~~
cupsfilters/driver.h:193:32: error: unknown type name 'ppd_file_t'
 extern cups_rgb_t *cupsRGBLoad(ppd_file_t *ppd,
                                ^~~~~~~~~~
cupsfilters/driver.h:218:34: error: unknown type name 'ppd_file_t'
 extern cups_cmyk_t *cupsCMYKLoad(ppd_file_t *ppd,
                                  ^~~~~~~~~~
cupsfilters/attr.c:36:1: error: unknown type name 'ppd_attr_t'
 ppd_attr_t *    /* O - Matching attribute or NULL */
 ^~~~~~~~~~
cupsfilters/attr.c:37:14: error: unknown type name 'ppd_file_t'
 cupsFindAttr(ppd_file_t *ppd,  /* I - PPD file */
              ^~~~~~~~~~
make[1]: *** [Makefile:2546: libcupsfilters_la-attr.lo] Error 1
In file included from cupsfilters/colormanager.c:29:0:
cupsfilters/colormanager.h:67:56: error: unknown type name 'ppd_file_t'
                                                        ppd_file_t *ppd);
                                                        ^~~~~~~~~~
In file included from cupsfilters/colormanager.c:30:0:
./cupsfilters/colord.h:39:44: error: unknown type name 'ppd_file_t'
 char  **colord_get_qualifier_for_ppd      (ppd_file_t *ppd);
                                            ^~~~~~~~~~
cupsfilters/colormanager.c:42:50: error: unknown type name 'ppd_file_t'
                                                  ppd_file_t *ppd);
                                                  ^~~~~~~~~~
cupsfilters/colormanager.c:43:50: error: unknown type name 'ppd_file_t'
 static char    *_get_ppd_icc_fallback           (ppd_file_t *ppd,
                                                  ^~~~~~~~~~
cupsfilters/colormanager.c: In function 'cmIsPrinterCmDisabled':
cupsfilters/colormanager.c:79:7: warning: implicit declaration of function 'fprintf' [-Wimplicit-function-declaration]
       fprintf(stderr,"DEBUG: Color Manager: Color management disabled by OS.\n");
       ^~~~~~~
cupsfilters/colormanager.c:79:7: warning: incompatible implicit declaration of built-in function 'fprintf'
In file included from cupsfilters/cmyk.c:37:0:
cupsfilters/driver.h:129:8: error: unknown type name 'ppd_attr_t'
 extern ppd_attr_t *cupsFindAttr(ppd_file_t *ppd, const char *name,
        ^~~~~~~~~~
cupsfilters/colormanager.c:79:7: note: include '' or provide a declaration of 'fprintf'
cupsfilters/driver.h:129:33: error: unknown type name 'ppd_file_t'
 extern ppd_attr_t *cupsFindAttr(ppd_file_t *ppd, const char *name,
                                 ^~~~~~~~~~
cupsfilters/colormanager.c:79:15: error: 'stderr' undeclared (first use in this function)
       fprintf(stderr,"DEBUG: Color Manager: Color management disabled by OS.\n");
               ^~~~~~
cupsfilters/colormanager.c:79:15: note: each undeclared identifier is reported only once for each function it appears in
cupsfilters/driver.h:159:32: error: unknown type name 'ppd_file_t'
 extern cups_lut_t *cupsLutLoad(ppd_file_t *ppd,
                                ^~~~~~~~~~
cupsfilters/colormanager.c: At top level:
cupsfilters/colormanager.c:90:24: error: unknown type name 'ppd_file_t'
                        ppd_file_t *ppd)           /* Optional PPD file for fallback profile */
                        ^~~~~~~~~~
cupsfilters/driver.h:193:32: error: unknown type name 'ppd_file_t'
 extern cups_rgb_t *cupsRGBLoad(ppd_file_t *ppd,
                                ^~~~~~~~~~
cupsfilters/colormanager.c: In function 'cmGetCupsColorCalibrateMode':
cupsfilters/colormanager.c:122:5: warning: incompatible implicit declaration of built-in function 'fprintf'
     fprintf(stderr, "DEBUG: Color Manager: %s\n", status ?
     ^~~~~~~
cupsfilters/driver.h:218:34: error: unknown type name 'ppd_file_t'
 extern cups_cmyk_t *cupsCMYKLoad(ppd_file_t *ppd,
                                  ^~~~~~~~~~
cupsfilters/colormanager.c:122:5: note: include '' or provide a declaration of 'fprintf'
cupsfilters/colormanager.c:122:13: error: 'stderr' undeclared (first use in this function)
     fprintf(stderr, "DEBUG: Color Manager: %s\n", status ?
             ^~~~~~
cupsfilters/colormanager.c: In function '_get_colord_printer_id':
cupsfilters/colormanager.c:185:7: warning: incompatible implicit declaration of built-in function 'fprintf'
       fprintf(stderr, "DEBUG: Color Manager: Invalid printer name.\n");
       ^~~~~~~
cupsfilters/colormanager.c:185:7: note: include '' or provide a declaration of 'fprintf'
cupsfilters/colormanager.c:185:15: error: 'stderr' undeclared (first use in this function)
       fprintf(stderr, "DEBUG: Color Manager: Invalid printer name.\n");
               ^~~~~~
cupsfilters/colormanager.c:191:5: warning: implicit declaration of function 'snprintf' [-Wimplicit-function-declaration]
     snprintf (printer_id, CM_MAX_FILE_LENGTH, "cups-%s", printer_name);
     ^~~~~~~~
cupsfilters/colormanager.c:191:5: warning: incompatible implicit declaration of built-in function 'snprintf'
cupsfilters/colormanager.c:191:5: note: include '' or provide a declaration of 'snprintf'
cupsfilters/colormanager.c: In function '_get_colord_printer_cm_status':
cupsfilters/colormanager.c:204:7: warning: incompatible implicit declaration of built-in function 'fprintf'
       fprintf(stderr, "DEBUG: Color Manager: Invalid printer name.\n");
       ^~~~~~~
cupsfilters/colormanager.c:204:7: note: include '' or provide a declaration of 'fprintf'
cupsfilters/colormanager.c:204:15: error: 'stderr' undeclared (first use in this function)
       fprintf(stderr, "DEBUG: Color Manager: Invalid printer name.\n");
               ^~~~~~
cupsfilters/colormanager.c: At top level:
cupsfilters/colormanager.c:227:21: error: unknown type name 'ppd_file_t'
                     ppd_file_t   *ppd)              /* PPD file */
                     ^~~~~~~~~~
cupsfilters/colormanager.c:285:24: error: unknown type name 'ppd_file_t'
 _get_ppd_icc_fallback (ppd_file_t *ppd, char **qualifier)
                        ^~~~~~~~~~
cupsfilters/cmyk.c:1027:14: error: unknown type name 'ppd_file_t'
 cupsCMYKLoad(ppd_file_t *ppd,  /* I - PPD file */
              ^~~~~~~~~~
make[1]: *** [Makefile:2574: libcupsfilters_la-colormanager.lo] Error 1
make[1]: *** [Makefile:2560: libcupsfilters_la-cmyk.lo] Error 1
In file included from cupsfilters/check.c:25:0:
cupsfilters/driver.h:129:8: error: unknown type name 'ppd_attr_t'
 extern ppd_attr_t *cupsFindAttr(ppd_file_t *ppd, const char *name,
        ^~~~~~~~~~
cupsfilters/driver.h:129:33: error: unknown type name 'ppd_file_t'
 extern ppd_attr_t *cupsFindAttr(ppd_file_t *ppd, const char *name,
                                 ^~~~~~~~~~
cupsfilters/driver.h:159:32: error: unknown type name 'ppd_file_t'
 extern cups_lut_t *cupsLutLoad(ppd_file_t *ppd,
                                ^~~~~~~~~~
cupsfilters/driver.h:193:32: error: unknown type name 'ppd_file_t'
 extern cups_rgb_t *cupsRGBLoad(ppd_file_t *ppd,
                                ^~~~~~~~~~
cupsfilters/driver.h:218:34: error: unknown type name 'ppd_file_t'
 extern cups_cmyk_t *cupsCMYKLoad(ppd_file_t *ppd,
                                  ^~~~~~~~~~
make[1]: *** [Makefile:2553: libcupsfilters_la-check.lo] Error 1
make: *** [Makefile:4785: check] Error 2
Traceback (most recent call last):
  File "/var/pisi/cups-filters/actions.py", line 28, in build
    autotools.make("check")
  File "/usr/lib/pisilinux/pisi/actionsapi/autotools.py", line 103, in make
    if system('make %s %s' % (get.makeJOBS(), parameters)):
  File "/usr/lib/pisilinux/pisi/actionsapi/shelltools.py", line 255, in system
    error(_("Command \"%s\" failed, return value was %d.") % (command, retValue))
  File "/usr/lib/pisilinux/pisi/actionsapi/__init__.py", line 27, in error
    raise Error(msg)
pisi.actionsapi.Error: Command "make -j5 check" failed, return value was 2.
[01;31mAction script error caught.
[0m[01;33m*** 1 error(s), 0 warning(s)
[0m[01;31mProgram terminated.
[0m

**Comment by Rmys** [comment]
yeniden derlendi cups wep aryüzü çalışıyor
