### ISSUE TITLE
BleachBit Açılmıyor

### ISSUE THREAD

**Issue by emreyilmaz-ay** [pisilinux/main#9325]
Bleachbiti açmaya çalıştığım zaman çalışmıyor konsoldan başlattığım zamanda bu hata çıktısını veriyor: Traceback (most recent call last):
  File "/usr/bin/bleachbit", line 26, in <module>
    from bleachbit.GuiPreferences import PreferencesDialog
  File "/usr/lib/python2.7/site-packages/bleachbit/GuiPreferences.py", line 31, in <module>
    from bleachbit import GuiBasic
  File "/usr/lib/python2.7/site-packages/bleachbit/GuiBasic.py", line 28, in <module>
    import gtk
ImportError: No module named gtk

**Comment by suvari** [comment]
fixed
